### PR TITLE
Create `match_id` for matches

### PR DESCRIPTION
**Pull request by Chefski**
Created a function generate_match_id with hashlib to create id. It'll make identifying the same matches from `live_match`, `upcoming_matches` and `results`.

### CODE REVIEW

**Comment by axsddlr** [comment]
> The scraping for the results will need to be taken from the vlr.gg home page. This'll get rid of the tournament icon....

elaborate. results are meant to scrape the icon as well

**Comment by Chefski** [comment]
Sorry I'll go over this again after my exams. Currently the id is made using the timestamp which is actually not present in results so I'll try another way.

**Comment by axsddlr** [comment]
@mentatbutler

**Comment by jakethekoenig** [comment]
> @mentatbutler

The bot currently only reacts to inline comments not issue comments on PRs. I'm hoping to add that feature this week

**Pull request closed without merging**
