### PR TITLE
Moved dependencies management to Poetry

### PR DESCRIPTION
**Pull request by haysberg**
Hello !

I recently started using your project for a personal project named [KAY/O](https://github.com/haysberg/kayo).

I saw that the depencies you were using were [not supported anymore](https://endoflife.date/python), and as I was looking to deploy this API locally on my home server to accelerate the scraping, so I decided to update the dependencies.

To manage them more efficiently, I decided to add [Poetry](https://python-poetry.org/). You can also setup Renovate on the repository to automatically update them.

Also, you will find a `docker-compose` file for local development, and one for deploying on a home server by pulling the image from the GitHub Docker registry.

If you want, I can also create a GitHub Action file to build a new image every time a new commit is made on the master branch.

Feel free to contact me for anything, I'm looking to actively help on this project !

### CODE REVIEW

**Comment by axsddlr** [comment]
sorry for the late reply on this, I have not been actively working on this project as scraping and base selectors have not changed. I'm willing to merge this if you add/update the README poetry deployment is not widely adopted yet. Also It would be great if you have time to make a github action.

**Comment by haysberg** [comment]
No problem ! I'll do it this weekend and update it in that case.

Also, I think it would be a great idea to configure Renovate on your repo to allow for dependencies update (you can make it automatic as well).

**Comment by axsddlr** [comment]
> No problem ! I'll do it this weekend and update it in that case.
> 
> Also, I think it would be a great idea to configure Renovate on your repo to allow for dependencies update (you can make it automatic as well).

whats the difference between that and Dependabot

**Comment by TheIGL1** [comment]
how can i use this api. i want to make a discord bot where you can find stats about player and team. but the api endpoint is not working properly.

**Comment by haysberg** [comment]
> I'm willing to merge this if you add/update the README poetry deployment is not widely adopted yet. Also It would be great if you have time to make a github action.

Sorry for the late reply, I am planning on doing this in the next few days. My CPU literally died on me a few weeks ago.

> what's the difference between that and Dependabot. I usually dont like auto updating dependencies because there can be something that breaks the application

You can find a comparison of features [on the Renovate Docs](https://docs.renovatebot.com/bot-comparison/#table-of-features). I would recommend having unit tests in the code, as there is not that much to test. That could allow us to be much more confident with dependency management.

**Comment by axsddlr** [comment]
closing due to lack of updates. May revisit in the future

**Pull request closed without merging**
